apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-new
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # Change the desired storage size here

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc-new   # Use the new PVC here

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins
#   namespace: jenkins
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins
#   template:
#     metadata:
#       labels:
#         app: jenkins
#     spec:
#       containers:
#       - name: jenkins
#         image: jenkins/jenkins:lts
#         ports:
#         - containerPort: 8080
#         - containerPort: 50000
#         volumeMounts:
#         - name: jenkins-home
#           mountPath: /var/jenkins_home
#       volumes:
#       - name: jenkins-home
#         emptyDir: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
#   namespace: jenkins
# spec:
#   selector:
#     app: jenkins
#   type: NodePort
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080
#     nodePort: 30000
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pvc
#   namespace: jenkins
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi